name: Build and Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'  # Trigger the workflow only if files in the frontend directory change
    branches:
      - main            # Trigger the workflow only on the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # Set the working directory to frontend

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version required for your project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the frontend
      - name: Build Frontend
        run: npm run build
        env: 
          CI: false        

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # Path to the build output directory
